name: Update Trailhead Stats

on:
  schedule:
    - cron: '0 0 1 * *' # Runs daily
  push:
    branches:
        - main

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: nabondance/trailhead-stats@v1.0.2
        with:
          trailhead-username: kcapehart
          display-type: 'text'
          display-file: 'README.md'
          file-format: 'md'
          card-path: './'